# Generated by Django 6.0.6 on 2026-06-13 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beekeeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('beekeeper', 'Beekeeper'), ('farm_user', 'Farm User'), ('viewer', 'Viewer')], default='beekeeper', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['email'], name='beekeeper_email_idx')],
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('established_date', models.DateField()),
                ('beekeeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='tracker.beekeeper')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hive_number', models.CharField(max_length=50)),
                ('hive_type', models.CharField(choices=[('langstroth', 'Langstroth'), ('top_bar', 'Top-bar'), ('log_hive', 'Log Hive'), ('kenya_top', 'Kenya Top-bar')], default='langstroth', max_length=50)),
                ('install_date', models.DateField()),
                ('queen_status', models.CharField(choices=[('mated', 'Mated'), ('new', 'New'), ('replaced', 'Replaced'), ('queenless', 'Queenless')], default='mated', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hives', to='tracker.farm')),
            ],
            options={
                'ordering': ['farm', 'hive_number'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('start_month', models.IntegerField()),
                ('end_month', models.IntegerField()),
            ],
            options={
                'ordering': ['year', 'start_month'],
                'unique_together': {('name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField()),
                ('yield_kg', models.FloatField()),
                ('notes', models.TextField(blank=True, default='')),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='tracker.hive')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvests', to='tracker.season')),
            ],
            options={
                'ordering': ['-harvest_date'],
            },
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['beekeeper'], name='farm_beekeeper_idx'),
        ),
        migrations.AddIndex(
            model_name='hive',
            index=models.Index(fields=['farm'], name='hive_farm_idx'),
        ),
        migrations.AddIndex(
            model_name='hive',
            index=models.Index(fields=['status'], name='hive_status_idx'),
        ),
        migrations.AddIndex(
            model_name='hive',
            index=models.Index(fields=['farm', 'status'], name='hive_farm_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hive',
            unique_together={('farm', 'hive_number')},
        ),
        migrations.AddIndex(
            model_name='harvest',
            index=models.Index(fields=['hive'], name='harvest_hive_idx'),
        ),
        migrations.AddIndex(
            model_name='harvest',
            index=models.Index(fields=['season'], name='harvest_season_idx'),
        ),
        migrations.AddIndex(
            model_name='harvest',
            index=models.Index(fields=['harvest_date'], name='harvest_date_idx'),
        ),
        migrations.AddIndex(
            model_name='harvest',
            index=models.Index(fields=['harvest_date', 'season'], name='harvest_date_season_idx'),
        ),
    ]
