# Generated by Django 6.0.6 on 2026-06-11 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beekeeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('start_month', models.IntegerField()),
                ('end_month', models.IntegerField()),
            ],
            options={
                'ordering': ['start_month'],
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('established_date', models.DateField()),
                ('beekeeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='tracker.beekeeper')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hive_number', models.CharField(max_length=50)),
                ('hive_type', models.CharField(choices=[('langstroth', 'Langstroth'), ('top_bar', 'Top-bar'), ('warre', 'Warré'), ('flow', 'Flow Hive')], default='langstroth', max_length=50)),
                ('install_date', models.DateField()),
                ('queen_status', models.CharField(choices=[('mated', 'Mated'), ('new', 'New'), ('replaced', 'Replaced'), ('queenless', 'Queenless')], default='mated', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hives', to='tracker.farm')),
            ],
            options={
                'ordering': ['farm', 'hive_number'],
                'unique_together': {('farm', 'hive_number')},
            },
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField()),
                ('yield_kg', models.FloatField()),
                ('honey_type', models.CharField(choices=[('wildflower', 'Wildflower'), ('clover', 'Clover'), ('acacia', 'Acacia'), ('manuka', 'Manuka'), ('buckwheat', 'Buckwheat'), ('other', 'Other')], default='wildflower', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='tracker.hive')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvests', to='tracker.season')),
            ],
            options={
                'ordering': ['-harvest_date'],
            },
        ),
    ]
