# Generated by Django 6.0.6 on 2026-06-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='beekeeper',
            index=models.Index(fields=['email'], name='beekeeper_email_idx'),
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['beekeeper'], name='farm_beekeeper_idx'),
        ),
        migrations.AddIndex(
            model_name='harvest',
            index=models.Index(fields=['hive'], name='harvest_hive_idx'),
        ),
        migrations.AddIndex(
            model_name='harvest',
            index=models.Index(fields=['season'], name='harvest_season_idx'),
        ),
        migrations.AddIndex(
            model_name='harvest',
            index=models.Index(fields=['harvest_date'], name='harvest_date_idx'),
        ),
        migrations.AddIndex(
            model_name='harvest',
            index=models.Index(fields=['harvest_date', 'season'], name='harvest_date_season_idx'),
        ),
        migrations.AddIndex(
            model_name='hive',
            index=models.Index(fields=['farm'], name='hive_farm_idx'),
        ),
        migrations.AddIndex(
            model_name='hive',
            index=models.Index(fields=['status'], name='hive_status_idx'),
        ),
        migrations.AddIndex(
            model_name='hive',
            index=models.Index(fields=['farm', 'status'], name='hive_farm_status_idx'),
        ),
    ]
