# Generated by Django 4.2.30 on 2026-06-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor_name', models.CharField(blank=True, default='', max_length=200)),
                ('actor_role', models.CharField(blank=True, default='', max_length=20)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export'), ('password_change', 'Password Change')], max_length=20)),
                ('resource', models.CharField(blank=True, default='', max_length=50)),
                ('resource_id', models.CharField(blank=True, default='', max_length=50)),
                ('detail', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_ts_idx'), models.Index(fields=['action'], name='audit_action_idx'), models.Index(fields=['actor_name'], name='audit_actor_idx')],
            },
        ),
    ]
